import { GameLevelType } from './base';

export default class Levels {
    public readonly GameLevels: GameLevelType[] = [
        {
            title: 'First A',
            description: 'Select the pawns',
            rightAnswer: 'pawn',
            code: ['<pawn />', '<pawn />'],
            figures: [
                { name: 'pawn', size: 'normal' },
                { name: 'pawn', size: 'normal' },
            ],
            target: [0, 1],
        },
        {
            title: 'Second A',
            rightAnswer: 'king',
            description: 'Select the king',
            code: ['<hat />', '<king />', '<flag />', '<rum />', '<king />'],
            figures: [
                { name: 'hat', size: 'normal' },
                { name: 'king', size: 'normal' },
                { name: 'flag', size: 'normal' },
                { name: 'rum', size: 'king' },
                { name: 'king', size: 'normal' },
            ],
            target: [1, 4],
        },
        {
            title: 'Third #id',
            rightAnswer: '#fancy',
            description: 'Select the fancy flag',
            code: ['<pawn />', '<flag id="fancy" />', '<flag />', '<queen />', '<rum />'],
            figures: [
                { name: 'pawn', size: 'normal' },
                { name: 'flag', size: 'normal' },
                { name: 'flag', size: 'normal' },
                { name: 'queen', size: 'normal' },
                { name: 'rum', size: 'normal' },
            ],
            target: [1],
        },
        {
            title: 'Fourth .className',
            rightAnswer: '.navigate',
            description: 'Select the navigate',
            code: ['<compass class = "navigate"/>', '<king />', '<flag />', '<rum />', '<compass class = "navigate"/>'],
            figures: [
                { name: 'compass', size: 'normal' },
                { name: 'king', size: 'normal' },
                { name: 'flag', size: 'normal' },
                { name: 'rum', size: 'normal' },
                { name: 'compass', size: 'normal' },
            ],
            target: [0, 4],
        },
        {
            title: 'Fifth A.className',
            description: 'Select the small rums',
            rightAnswer: 'rum.small',
            code: [
                '<flag />',
                '<rum class = "small" />',
                '<rum />',
                '<compass />',
                '<rum class = "small" />',
                '<hat />',
            ],
            figures: [
                { name: 'flag', size: 'normal' },
                { name: 'rum', size: 'small' },
                { name: 'rum', size: 'normal' },
                { name: 'compass', size: 'normal' },
                { name: 'rum', size: 'small' },
                { name: 'hat', size: 'normal' },
            ],
            target: [1, 4],
        },
        {
            title: 'Sixth A,B',
            description: 'Select all the queens and kings',
            rightAnswer: 'queen,king',
            code: ['<hat />', '<queen />', '<king />', '<queen class = "small" />', '<compass />'],
            figures: [
                { name: 'hat', size: 'normal' },
                { name: 'queen', size: 'normal' },
                { name: 'king', size: 'normal' },
                { name: 'queen', size: 'small' },
                { name: 'compass', size: 'normal' },
            ],
            target: [1, 2, 3],
        },
        {
            title: 'Seventh *',
            description: 'Select all the things!',
            rightAnswer: '*',
            code: ['<rum />', '<hat />', '<queen />', '<flag class = "small"/>', '<compass />', '<flag />'],
            figures: [
                { name: 'rum', size: 'normal' },
                { name: 'hat', size: 'normal' },
                { name: 'queen', size: 'normal' },
                { name: 'flag', size: 'small' },
                { name: 'compass', size: 'normal' },
                { name: 'flag', size: 'normal' },
            ],
            target: [0, 1, 2, 3, 4, 5],
        },
        {
            title: 'Eight A + B',
            description: `Select every pawn that's next to a flag`,
            rightAnswer: 'flag + pawn',
            code: [
                '<rum />',
                '<flag />',
                '<pawn class = "small"/>',
                '<flag />',
                '<pawn />',
                '<pawn class = "small"/>',
                '<pawn class = "small"/>',
            ],
            figures: [
                { name: 'rum', size: 'normal' },
                { name: 'flag', size: 'normal' },
                { name: 'pawn', size: 'small' },
                { name: 'flag', size: 'normal' },
                { name: 'pawn', size: 'normal' },
                { name: 'pawn', size: 'small' },
                { name: 'pawn', size: 'small' },
            ],
            target: [2, 4],
        },
        {
            title: 'Ninth A ~ B',
            description: 'Select the hats beside the rum',
            rightAnswer: 'rum ~ hat',
            code: [
                '<compass />',
                '<rum />',
                '<hat class = "small" />',
                '<hat />',
                '<flag />',
                '<hat class = "small" />',
                '<hat />',
            ],
            figures: [
                { name: 'compass', size: 'normal' },
                { name: 'rum', size: 'normal' },
                { name: 'hat', size: 'small' },
                { name: 'hat', size: 'normal' },
                { name: 'flag', size: 'normal' },
                { name: 'hat', size: 'small' },
                { name: 'hat', size: 'normal' },
            ],
            target: [2, 3],
        },
        {
            title: 'Tenth :first-of-type',
            description: 'Select first compass',
            rightAnswer: 'compass:first-of-type',
            code: [
                '<flag />',
                '<compass />',
                '<compass class = "small" />',
                '<compass />',
                '<compass class = "small" />',
                '<rum />',
            ],
            figures: [
                { name: 'flag', size: 'normal' },
                { name: 'compass', size: 'normal' },
                { name: 'compass', size: 'small' },
                { name: 'compass', size: 'normal' },
                { name: 'compass', size: 'small' },
                { name: 'rum', size: 'normal' },
            ],
            target: [1],
        },
        {
            title: 'Eleven A B, A B',
            description: 'Select elements on papers',
            rightAnswer: 'paper compass, paper flag',
            code: [
                '<paper> <compass /> </paper>',
                '<rum />',
                '<hat class = "small" />',
                '<hat />',
                '<paper> <flag /> </paper>',
            ],
            figures: [
                { name: 'compass', size: 'normal', inner: { name: 'paper', size: 'paper' } },
                { name: 'rum', size: 'normal' },
                { name: 'compass', size: 'small' },
                { name: 'hat', size: 'normal' },
                { name: 'flag', size: 'normal', inner: { name: 'hat', size: 'TestSize' } },
            ],
            target: [0, 4],
        },
    ];
}
